# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SangTaek Lim
email: lst0415@daum.net
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
  
baseurl:  # the subpath of your site, e.g. /blog
url: "http://webjeda.com" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: SangTaek Lim

copyright:
   name: SangTaek Lim
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus: yes
disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/sangtaek.lim.9
quora:
twitter:
github: http://github.com/SangTaekLim
email: lst0415@daum.net

#facebook like box
fb-like-box: no
fb-app-id:
fb-page-url:
fb-page-title:

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

